# name of the application
APPLICATION = air-quality

# If no BOARD is found in the environment, use this default:
BOARD ?= lora-e5-dev

USEMODULE += sgp40

DEVELHELP ?= 1

# Change this to 0 show compiler invocation lines by default:
QUIET ?= 1

include $(RIOTBASE)/Makefile.include
